# Permalinks
permalink:        /post/:title.html

# Setup
url:              ""
img_url:          https://cdn.jsdelivr.net/gh/infp/infp.github.io/images

# Set to '' in case of hosting on `https://<your-github-name>.github.io`
baseurl:          ''

title:            Jason的博客

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  念天地之悠悠，独怆然而涕下

notification:     |

plugins:
  - jekyll-seo-tag
  - jekyll-feed
# Google Analytics tracking ID
# TODO: 如果使用本主题，请务必替换此处的 Google 统计代码，否则你的站点将无法获得统计数据
#analytics:        'UA-32028925-2'

# Fallback image and color if not overwritten for tag or post
image:            /public/images/flower.jpg
color:            '#dc322f'
搜索: "search"
author:
  name:           刘的
  email:          tongrui996@gmail.com
  photo:          /public/images/cat.jpg
  github:         liudi96
  linkedin:       liudi96
  facebook:       liudi
  steam:          originals


  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    我是Jason，乐于分享，喜欢思考，请大家多多指教！


compress_html:
  clippings:      all
  comments:       ["<!--", "-->"]
  endings:        all
  startings:      [html, head, body]

sass:
  sass_dir:       /public/css
  style:          compressed
