# Site settings
  title: My Blog
  SEOTitle: 我的博客 | My Blog
  header-img: img/home-bg.jpg
  email: tongrui996@gmail.com
  description: "记录所思、所为"
  keyword: "我的博客"
  url: "http://liudi96.github.io"          # name改成你的ID
  baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
  github_repo: "https://github.com/liudi96/liudi96.github.io.git" # 用你的ID替换name

  # Sidebar settings
  sidebar: true                           # whether or not using Sidebar.
  sidebar-about-description: "苟利国家生死以，岂因祸福避趋之~"
  sidebar-avatar: /img/avatar_m.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

  # SNS settings
  RSS: false
  # weibo_username: 暂无
  zhihu_username:     暂无
  github_username:    暂无
  facebook_username:  暂无
  jianshu_username:   暂无
  #twitter_username: 暂无

  # Featured Tags
  featured-tags: true                     # 是否使用首页标签
  featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页